site_name: pyjsta

repo_url: https://github.com/jsta/pyjsta/

nav:
    - Home: index.md
    - API:
      - rstats clone functions: rstats.md
      - table functions: tables.md    

theme:
  name: "readthedocs"

plugins:
- search
- mkdocstrings:
      