site_name: pyjsta

repo_url: https://github.com/jsta/pyjsta/

nav:
    - Home: index.md
    - API: api.md

theme:
  name: "readthedocs"

plugins:
- search
- mkdocstrings:
      watch:
        - pyjsta        