name: docs

on:
  push:
    paths:
      - pyjsta/**
      - docs/**
      - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '>3.6.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocstrings
    - name: Install package
      run: |
        pip install -e .
    - name: Deploy
      run: |
        git pull
        mkdocs gh-deploy
        